### ISSUE TITLE
Main menu music not on music slider.

### ISSUE THREAD

**Issue by 111112oo** [tf2classic/tf2classic-issue-tracker#154]
Self explanatory title. The title screen music needs the # character behind the sound path in the soundscript for it.

**Comment by bobatealee** [comment]
fixed in next version

**Comment by 111112oo** [comment]
yay!

**Comment by 111112oo** [comment]
This was not fixed/broken again in the latest update, the music on the menu is not affected by the music slider.
